### ISSUE TITLE
V11 starter does not start up when following /start instructions.

### ISSUE THREAD

**Issue by Peppe** [vaadin/base-starter-react#15]
On https://vaadin.com/start/latest/react, the instructions to get the starter to use are the following. 
1. Extract zip
2. Ensure yarn is installed
3. `yarn install`
4. `yarn start`

Following these instructions, you get a huge error on your screen when it is loaded in the browser, and the app is unusable.

> Element ref was specified as a string (text) but no owner was set. This could happen for one of the following reasons:
> 1. You may be adding a ref to a functional component
> 2. You may be adding a ref to a component that was not created inside a component's render method
> 3. You have multiple copies of React loaded
> See https://fb.me/react-refs-must-have-owner for more information.

This can be fixed with an `bower install` between 3 and 4.

Furthermore, the README.md has another list of instructions.

1. install bower
2. `npm install`
3. `bower install`
4. `npm start`

These instructions work out of the box. 

### Please choose one set of instructions that work, and put the same set in both the README and /start/latest/react
(and other versions than latest if they are broken as well).

**Comment by web-padawan** [comment]
The readme of the starter contains `bower install`:
https://github.com/vaadin/base-starter-react/blob/v11/README.md#running-the-application

**Comment by web-padawan** [comment]
> the zip file should be generated from https://github.com/vaadin/base-starter-react/archive/p3-preview.zip

It it generated from V10 and V11 branches, respectively. Please see #12 and #13 for description why we cannot simply use P3 versions for now.

My opinion is that we should have a working Webpack config to be used with all the starters. Not sure how much are we ready to invest into this, for now I'm recommending users to use my own starter:
https://github.com/web-padawan/polymer3-webpack-starter

I've put significantly more effort into it, both CF and personal evening coding, and I believe that is how the proper starter should look like.

**Comment by amahdy** [comment]
At least `yarn install` works.

Right now there is a big inconsistency between instructions listed on the `/start` pages and the downloaded zip file. So we need to at least download a properly working zip file.
1. We do not want to have `bower` instructions highlighted on our website.
1. We want to provide a working version of the source code with latest p3 features for front-end developers that do not care about Vaadin platform version.

Please switch the download to use the `p3-preview` zip file for now. Thanks

**Comment by web-padawan** [comment]
> We want to provide a working version of the source code with latest p3 features for front-end developers that do not care about Vaadin platform version.
It is not working. Installing dependencies obviously works, but building does not.

Once we release V12 with the official Polymer 3 support, we will be able to switch starters to use it in case if these issues are fixed by that time (some of those are related to React tools).

**Comment by amahdy** [comment]
Good, but for now, `/start` is a public web page and must contain a working zip file. If you can fix `#3572` would be greatly appreciated, otherwise I need to talk to someone from the website team.

**Comment by web-padawan** [comment]
The zip file there is working, they should update starting instructions to match readme.

**Comment by amahdy** [comment]
> 1. We do not want to have bower instructions highlighted on our website.

Vaadin 12 still has few months to go.

**Comment by web-padawan** [comment]
Fixed by #16 on the `p3-preview` branch, will merge to `master` once other starters are fixed.
